[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "erasure_sim_decoding"
version = "0.1.0"
description = "for surface code erasure detection simulation"
authors = [
    {name = Jiakai Wang", email = "jwang2648@wisc.edu"},
]
